import type { Language } from './i18n';

const copy: Record<Language, any> = {
  fr: { close:'Fermer le formulaire', title:'Titre de votre demande', titlePlaceholder:'Ex : inscription entreprise, candidat emploi, chauffeur privé, professeur...', phone:'Téléphone', email:'Email', emailPlaceholder:'votre@email.com', message:'Message', messagePlaceholder:'Expliquez brièvement votre demande, votre activité ou votre question...', requiredTitle:'Le titre de votre demande est obligatoire.', requiredContact:'Merci d’indiquer au moins un téléphone ou un email.', invalidEmail:'Format email invalide.', requiredMessage:'Merci de décrire brièvement votre demande.', submitError:'Une erreur est survenue. Veuillez réessayer.', unexpectedError:'Une erreur inattendue est survenue. Veuillez réessayer.' },
  en: { close:'Close form', title:'Request title', titlePlaceholder:'E.g. business registration, job candidate, private driver, teacher...', phone:'Phone', email:'Email', emailPlaceholder:'your@email.com', message:'Message', messagePlaceholder:'Briefly describe your request, activity, or question...', requiredTitle:'The request title is required.', requiredContact:'Please provide at least a phone number or email.', invalidEmail:'Invalid email format.', requiredMessage:'Please briefly describe your request.', submitError:'An error occurred. Please try again.', unexpectedError:'An unexpected error occurred. Please try again.' },
  ar: { close:'إغلاق النموذج', title:'عنوان الطلب', titlePlaceholder:'مثال: تسجيل مؤسسة، مترشح للعمل، سائق خاص، أستاذ...', phone:'الهاتف', email:'البريد الإلكتروني', emailPlaceholder:'your@email.com', message:'الرسالة', messagePlaceholder:'صف بإيجاز طلبك أو نشاطك أو سؤالك...', requiredTitle:'عنوان الطلب مطلوب.', requiredContact:'يرجى إدخال رقم هاتف أو بريد إلكتروني على الأقل.', invalidEmail:'صيغة البريد الإلكتروني غير صالحة.', requiredMessage:'يرجى وصف طلبك بإيجاز.', submitError:'حدث خطأ. يرجى المحاولة مرة أخرى.', unexpectedError:'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.' },
  it: { close:'Chiudi il modulo', title:'Titolo della richiesta', titlePlaceholder:'Es.: iscrizione impresa, candidato lavoro, autista privato, insegnante...', phone:'Telefono', email:'Email', emailPlaceholder:'tua@email.com', message:'Messaggio', messagePlaceholder:'Descrivi brevemente la richiesta, l’attività o la domanda...', requiredTitle:'Il titolo della richiesta è obbligatorio.', requiredContact:'Indica almeno un telefono o un’email.', invalidEmail:'Formato email non valido.', requiredMessage:'Descrivi brevemente la richiesta.', submitError:'Si è verificato un errore. Riprova.', unexpectedError:'Si è verificato un errore imprevisto. Riprova.' },
  ru: { close:'Закрыть форму', title:'Заголовок запроса', titlePlaceholder:'Например: регистрация компании, кандидат на работу, частный водитель, преподаватель...', phone:'Телефон', email:'Email', emailPlaceholder:'your@email.com', message:'Сообщение', messagePlaceholder:'Кратко опишите запрос, деятельность или вопрос...', requiredTitle:'Укажите заголовок запроса.', requiredContact:'Укажите хотя бы телефон или email.', invalidEmail:'Некорректный формат email.', requiredMessage:'Кратко опишите запрос.', submitError:'Произошла ошибка. Попробуйте снова.', unexpectedError:'Произошла непредвиденная ошибка. Попробуйте снова.' }
};

export function getFooterRequestTranslations(language: Language) {
  return copy[language] || copy.fr;
}
