import type { Language } from './i18n';

const copy: Record<Language, any> = {
  fr: { heading:'Demande d’information / inscription', intro:'Une question, une inscription ou une demande professionnelle ? Envoyez-nous votre demande, notre équipe vous recontactera rapidement.', close:'Fermer le formulaire', success:'Merci ! Votre demande a été envoyée avec succès. Nous vous recontacterons rapidement.', title:'Titre de votre demande', titlePlaceholder:'Ex : inscription entreprise, candidat emploi, chauffeur privé, professeur...', phone:'Téléphone', email:'Email', emailPlaceholder:'votre@email.com', contactHint:'Merci d’indiquer au moins un moyen de contact : téléphone ou email.', message:'Message', messagePlaceholder:'Expliquez brièvement votre demande, votre activité ou votre question...', cancel:'Annuler', sending:'Envoi en cours...', submit:'Envoyer ma demande', requiredTitle:'Le titre de votre demande est obligatoire.', requiredContact:'Merci d’indiquer au moins un téléphone ou un email.', invalidEmail:'Format email invalide.', requiredMessage:'Merci de décrire brièvement votre demande.', submitError:'Une erreur est survenue. Veuillez réessayer.', unexpectedError:'Une erreur inattendue est survenue. Veuillez réessayer.' },
  en: { heading:'Information / registration request', intro:'A question, registration, or professional request? Send us your request and our team will contact you shortly.', close:'Close form', success:'Thank you! Your request has been sent successfully. We will contact you shortly.', title:'Request title', titlePlaceholder:'E.g. business registration, job candidate, private driver, teacher...', phone:'Phone', email:'Email', emailPlaceholder:'your@email.com', contactHint:'Please provide at least one contact method: phone or email.', message:'Message', messagePlaceholder:'Briefly describe your request, activity, or question...', cancel:'Cancel', sending:'Sending...', submit:'Send my request', requiredTitle:'The request title is required.', requiredContact:'Please provide at least a phone number or email.', invalidEmail:'Invalid email format.', requiredMessage:'Please briefly describe your request.', submitError:'An error occurred. Please try again.', unexpectedError:'An unexpected error occurred. Please try again.' },
  ar: { heading:'طلب معلومات / تسجيل', intro:'لديك سؤال أو تسجيل أو طلب مهني؟ أرسل طلبك وسيتواصل معك فريقنا قريباً.', close:'إغلاق النموذج', success:'شكراً! تم إرسال طلبك بنجاح وسنتواصل معك قريباً.', title:'عنوان الطلب', titlePlaceholder:'مثال: تسجيل مؤسسة، مترشح للعمل، سائق خاص، أستاذ...', phone:'الهاتف', email:'البريد الإلكتروني', emailPlaceholder:'your@email.com', contactHint:'يرجى إدخال وسيلة اتصال واحدة على الأقل: الهاتف أو البريد الإلكتروني.', message:'الرسالة', messagePlaceholder:'صف بإيجاز طلبك أو نشاطك أو سؤالك...', cancel:'إلغاء', sending:'جارٍ الإرسال...', submit:'إرسال طلبي', requiredTitle:'عنوان الطلب مطلوب.', requiredContact:'يرجى إدخال رقم هاتف أو بريد إلكتروني على الأقل.', invalidEmail:'صيغة البريد الإلكتروني غير صالحة.', requiredMessage:'يرجى وصف طلبك بإيجاز.', submitError:'حدث خطأ. يرجى المحاولة مرة أخرى.', unexpectedError:'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.' },
  it: { heading:'Richiesta di informazioni / iscrizione', intro:'Hai una domanda, un’iscrizione o una richiesta professionale? Inviaci la tua richiesta e il nostro team ti contatterà rapidamente.', close:'Chiudi il modulo', success:'Grazie! La tua richiesta è stata inviata con successo. Ti contatteremo rapidamente.', title:'Titolo della richiesta', titlePlaceholder:'Es.: iscrizione impresa, candidato lavoro, autista privato, insegnante...', phone:'Telefono', email:'Email', emailPlaceholder:'tua@email.com', contactHint:'Indica almeno un mezzo di contatto: telefono o email.', message:'Messaggio', messagePlaceholder:'Descrivi brevemente la richiesta, l’attività o la domanda...', cancel:'Annulla', sending:'Invio in corso...', submit:'Invia la mia richiesta', requiredTitle:'Il titolo della richiesta è obbligatorio.', requiredContact:'Indica almeno un telefono o un’email.', invalidEmail:'Formato email non valido.', requiredMessage:'Descrivi brevemente la richiesta.', submitError:'Si è verificato un errore. Riprova.', unexpectedError:'Si è verificato un errore imprevisto. Riprova.' },
  ru: { heading:'Запрос информации / регистрация', intro:'Есть вопрос, регистрация или деловой запрос? Отправьте заявку, и наша команда скоро свяжется с вами.', close:'Закрыть форму', success:'Спасибо! Ваш запрос успешно отправлен. Мы скоро свяжемся с вами.', title:'Заголовок запроса', titlePlaceholder:'Например: регистрация компании, кандидат на работу, частный водитель, преподаватель...', phone:'Телефон', email:'Email', emailPlaceholder:'your@email.com', contactHint:'Укажите хотя бы один способ связи: телефон или email.', message:'Сообщение', messagePlaceholder:'Кратко опишите запрос, деятельность или вопрос...', cancel:'Отмена', sending:'Отправка...', submit:'Отправить запрос', requiredTitle:'Укажите заголовок запроса.', requiredContact:'Укажите хотя бы телефон или email.', invalidEmail:'Некорректный формат email.', requiredMessage:'Кратко опишите запрос.', submitError:'Произошла ошибка. Попробуйте снова.', unexpectedError:'Произошла непредвиденная ошибка. Попробуйте снова.' }
};

export function getFooterRequestTranslations(language: Language) {
  return copy[language] || copy.fr;
}
