import type { Language } from './i18n';

const candidate: Record<Language, any> = {
  fr:{login:'Vous devez être connecté pour voir vos recommandations',noProfile:"Aucun profil candidat trouvé. Veuillez créer votre profil candidat d'abord.",loadError:'Erreur lors du chargement des recommandations',already:'Vous avez déjà postulé à cette offre',success:'Candidature envoyée avec succès !',applyError:"Erreur lors de l'envoi de la candidature",loading:'Chargement de vos recommandations...',error:'Erreur',createProfile:'Créer mon profil candidat',title:'Offres recommandées pour vous',subtitle:"Découvrez les offres d'emploi qui correspondent le mieux à votre profil",empty:'Aucune offre correspondante pour le moment',emptyHint:'Complétez votre profil et ajoutez plus de compétences pour améliorer vos recommandations.',why:'Pourquoi cette offre ?',salaryMonth:'TND/mois',view:'Voir l’offre',working:'En cours...',apply:'Postuler'},
  en:{login:'You must be signed in to view your recommendations',noProfile:'No candidate profile found. Please create your candidate profile first.',loadError:'Error loading recommendations',already:'You have already applied for this job',success:'Application sent successfully!',applyError:'Error sending the application',loading:'Loading your recommendations...',error:'Error',createProfile:'Create my candidate profile',title:'Recommended jobs for you',subtitle:'Discover the job offers that best match your profile',empty:'No matching jobs at the moment',emptyHint:'Complete your profile and add more skills to improve your recommendations.',why:'Why this job?',salaryMonth:'TND/month',view:'View job',working:'In progress...',apply:'Apply'},
  ar:{login:'يجب تسجيل الدخول لعرض توصياتك',noProfile:'لم يتم العثور على ملف مترشح. يرجى إنشاء ملفك أولاً.',loadError:'خطأ أثناء تحميل التوصيات',already:'لقد ترشحت بالفعل لهذه الوظيفة',success:'تم إرسال الترشح بنجاح!',applyError:'خطأ أثناء إرسال الترشح',loading:'جارٍ تحميل توصياتك...',error:'خطأ',createProfile:'إنشاء ملف مترشح',title:'وظائف موصى بها لك',subtitle:'اكتشف عروض العمل الأكثر تطابقاً مع ملفك',empty:'لا توجد عروض مطابقة حالياً',emptyHint:'أكمل ملفك وأضف المزيد من المهارات لتحسين التوصيات.',why:'لماذا هذه الوظيفة؟',salaryMonth:'د.ت/شهر',view:'عرض الوظيفة',working:'جارٍ التنفيذ...',apply:'ترشح'},
  it:{login:'Devi accedere per vedere i tuoi suggerimenti',noProfile:'Nessun profilo candidato trovato. Crea prima il tuo profilo.',loadError:'Errore nel caricamento dei suggerimenti',already:'Hai già candidato per questa offerta',success:'Candidatura inviata con successo!',applyError:'Errore durante l’invio della candidatura',loading:'Caricamento dei suggerimenti...',error:'Errore',createProfile:'Crea il mio profilo candidato',title:'Offerte consigliate per te',subtitle:'Scopri le offerte di lavoro più adatte al tuo profilo',empty:'Nessuna offerta corrispondente al momento',emptyHint:'Completa il profilo e aggiungi altre competenze per migliorare i suggerimenti.',why:'Perché questa offerta?',salaryMonth:'TND/mese',view:'Vedi offerta',working:'In corso...',apply:'Candidati'},
  ru:{login:'Войдите, чтобы увидеть рекомендации',noProfile:'Профиль кандидата не найден. Сначала создайте профиль кандидата.',loadError:'Ошибка загрузки рекомендаций',already:'Вы уже откликнулись на эту вакансию',success:'Отклик успешно отправлен!',applyError:'Ошибка отправки отклика',loading:'Загрузка рекомендаций...',error:'Ошибка',createProfile:'Создать профиль кандидата',title:'Рекомендуемые вакансии',subtitle:'Найдите вакансии, которые лучше всего подходят вашему профилю',empty:'Подходящих вакансий пока нет',emptyHint:'Заполните профиль и добавьте навыки, чтобы улучшить рекомендации.',why:'Почему эта вакансия?',salaryMonth:'TND/месяц',view:'Посмотреть вакансию',working:'Выполняется...',apply:'Откликнуться'}
};

const company: Record<Language, any> = {
  fr:{login:'Vous devez être connecté pour voir les candidats',loading:'Recherche des candidats correspondants...',error:'Erreur',messagePlaceholder:'Votre message...',send:'Envoyer'},
  en:{login:'You must be signed in to view candidates',loading:'Searching for matching candidates...',error:'Error',messagePlaceholder:'Your message...',send:'Send'},
  ar:{login:'يجب تسجيل الدخول لعرض المترشحين',loading:'جارٍ البحث عن المترشحين المطابقين...',error:'خطأ',messagePlaceholder:'رسالتك...',send:'إرسال'},
  it:{login:'Devi accedere per vedere i candidati',loading:'Ricerca dei candidati corrispondenti...',error:'Errore',messagePlaceholder:'Il tuo messaggio...',send:'Invia'},
  ru:{login:'Войдите, чтобы увидеть кандидатов',loading:'Поиск подходящих кандидатов...',error:'Ошибка',messagePlaceholder:'Ваше сообщение...',send:'Отправить'}
};

export const getCandidateJobMatchTranslations = (language: Language) => candidate[language] || candidate.fr;
export const getCompanyJobMatchTranslations = (language: Language) => company[language] || company.fr;
