import type { Language } from './i18n';

const candidate: Record<Language, any> = {
  fr:{login:'Vous devez être connecté pour voir vos recommandations',noProfile:"Aucun profil candidat trouvé. Veuillez créer votre profil candidat d'abord.",loadError:'Erreur lors du chargement des recommandations',already:'Vous avez déjà postulé à cette offre',success:'Candidature envoyée avec succès !',applyError:"Erreur lors de l'envoi de la candidature",loading:'Chargement de vos recommandations...',error:'Erreur',createProfile:'Créer mon profil candidat',title:'Offres recommandées pour vous',subtitle:"Découvrez les offres d'emploi qui correspondent le mieux à votre profil",empty:'Aucune offre correspondante pour le moment',emptyHint:'Complétez votre profil et ajoutez plus de compétences pour améliorer vos recommandations.',why:'Pourquoi cette offre ?',salaryMonth:'TND/mois',view:'Voir l’offre',working:'En cours...',apply:'Postuler'},
  en:{login:'You must be signed in to view your recommendations',noProfile:'No candidate profile found. Please create your candidate profile first.',loadError:'Error loading recommendations',already:'You have already applied for this job',success:'Application sent successfully!',applyError:'Error sending the application',loading:'Loading your recommendations...',error:'Error',createProfile:'Create my candidate profile',title:'Recommended jobs for you',subtitle:'Discover the job offers that best match your profile',empty:'No matching jobs at the moment',emptyHint:'Complete your profile and add more skills to improve your recommendations.',why:'Why this job?',salaryMonth:'TND/month',view:'View job',working:'In progress...',apply:'Apply'},
  ar:{login:'يجب تسجيل الدخول لعرض توصياتك',noProfile:'لم يتم العثور على ملف مترشح. يرجى إنشاء ملفك أولاً.',loadError:'خطأ أثناء تحميل التوصيات',already:'لقد ترشحت بالفعل لهذه الوظيفة',success:'تم إرسال الترشح بنجاح!',applyError:'خطأ أثناء إرسال الترشح',loading:'جارٍ تحميل توصياتك...',error:'خطأ',createProfile:'إنشاء ملف مترشح',title:'وظائف موصى بها لك',subtitle:'اكتشف عروض العمل الأكثر تطابقاً مع ملفك',empty:'لا توجد عروض مطابقة حالياً',emptyHint:'أكمل ملفك وأضف المزيد من المهارات لتحسين التوصيات.',why:'لماذا هذه الوظيفة؟',salaryMonth:'د.ت/شهر',view:'عرض الوظيفة',working:'جارٍ التنفيذ...',apply:'ترشح'},
  it:{login:'Devi accedere per vedere i tuoi suggerimenti',noProfile:'Nessun profilo candidato trovato. Crea prima il tuo profilo.',loadError:'Errore nel caricamento dei suggerimenti',already:'Hai già candidato per questa offerta',success:'Candidatura inviata con successo!',applyError:'Errore durante l’invio della candidatura',loading:'Caricamento dei suggerimenti...',error:'Errore',createProfile:'Crea il mio profilo candidato',title:'Offerte consigliate per te',subtitle:'Scopri le offerte di lavoro più adatte al tuo profilo',empty:'Nessuna offerta corrispondente al momento',emptyHint:'Completa il profilo e aggiungi altre competenze per migliorare i suggerimenti.',why:'Perché questa offerta?',salaryMonth:'TND/mese',view:'Vedi offerta',working:'In corso...',apply:'Candidati'},
  ru:{login:'Войдите, чтобы увидеть рекомендации',noProfile:'Профиль кандидата не найден. Сначала создайте профиль кандидата.',loadError:'Ошибка загрузки рекомендаций',already:'Вы уже откликнулись на эту вакансию',success:'Отклик успешно отправлен!',applyError:'Ошибка отправки отклика',loading:'Загрузка рекомендаций...',error:'Ошибка',createProfile:'Создать профиль кандидата',title:'Рекомендуемые вакансии',subtitle:'Найдите вакансии, которые лучше всего подходят вашему профилю',empty:'Подходящих вакансий пока нет',emptyHint:'Заполните профиль и добавьте навыки, чтобы улучшить рекомендации.',why:'Почему эта вакансия?',salaryMonth:'TND/месяц',view:'Посмотреть вакансию',working:'Выполняется...',apply:'Откликнуться'}
};

const company: Record<Language, any> = {
  fr:{login:'Vous devez être connecté pour voir les candidats',notFound:"Offre d'emploi non trouvée",forbidden:"Vous n'avez pas accès aux candidats de cette offre",loadError:'Erreur lors du chargement des candidats',loading:'Recherche des candidats correspondants...',error:'Erreur',title:'Candidats correspondants',forJob:"Pour l'offre :",empty:'Aucun candidat correspondant pour le moment',emptyHint:'Les candidats dont le profil correspond apparaîtront ici automatiquement.',beginner:'Débutant',oneYear:"1 an d'expérience",years:'ans d’expérience',why:'Pourquoi ce candidat ?',contact:'Contacter',contactTitle:'Contacter',note:'Note :',noteText:'Cette fonctionnalité de messagerie est en cours de développement. Pour le moment, le message sera simulé.',messagePlaceholder:'Votre message...',cancel:'Annuler',sending:'Envoi...',send:'Envoyer',devMessage:'Fonctionnalité de messagerie en cours de développement. Le candidat sera notifié prochainement.',sendError:"Erreur lors de l'envoi du message"},
  en:{login:'You must be signed in to view candidates',notFound:'Job offer not found',forbidden:'You do not have access to candidates for this job',loadError:'Error loading candidates',loading:'Searching for matching candidates...',error:'Error',title:'Matching candidates',forJob:'For the job:',empty:'No matching candidates at the moment',emptyHint:'Candidates whose profiles match will appear here automatically.',beginner:'Beginner',oneYear:'1 year of experience',years:'years of experience',why:'Why this candidate?',contact:'Contact',contactTitle:'Contact',note:'Note:',noteText:'This messaging feature is under development. For now, the message will be simulated.',messagePlaceholder:'Your message...',cancel:'Cancel',sending:'Sending...',send:'Send',devMessage:'Messaging is under development. The candidate will be notified soon.',sendError:'Error sending the message'},
  ar:{login:'يجب تسجيل الدخول لعرض المترشحين',notFound:'عرض العمل غير موجود',forbidden:'ليس لديك صلاحية الوصول إلى مترشحي هذا العرض',loadError:'خطأ أثناء تحميل المترشحين',loading:'جارٍ البحث عن المترشحين المطابقين...',error:'خطأ',title:'المترشحون المطابقون',forJob:'للعرض:',empty:'لا يوجد مترشحون مطابقون حالياً',emptyHint:'سيظهر هنا المترشحون الذين تتطابق ملفاتهم تلقائياً.',beginner:'مبتدئ',oneYear:'سنة خبرة',years:'سنوات خبرة',why:'لماذا هذا المترشح؟',contact:'اتصال',contactTitle:'الاتصال بـ',note:'ملاحظة:',noteText:'ميزة المراسلة قيد التطوير. حالياً سيتم محاكاة الرسالة.',messagePlaceholder:'رسالتك...',cancel:'إلغاء',sending:'جارٍ الإرسال...',send:'إرسال',devMessage:'ميزة المراسلة قيد التطوير وسيتم إشعار المترشح قريباً.',sendError:'خطأ أثناء إرسال الرسالة'},
  it:{login:'Devi accedere per vedere i candidati',notFound:'Offerta di lavoro non trovata',forbidden:'Non hai accesso ai candidati per questa offerta',loadError:'Errore nel caricamento dei candidati',loading:'Ricerca dei candidati corrispondenti...',error:'Errore',title:'Candidati corrispondenti',forJob:"Per l'offerta:",empty:'Nessun candidato corrispondente al momento',emptyHint:'I candidati con un profilo corrispondente appariranno automaticamente qui.',beginner:'Principiante',oneYear:'1 anno di esperienza',years:'anni di esperienza',why:'Perché questo candidato?',contact:'Contatta',contactTitle:'Contatta',note:'Nota:',noteText:'Questa funzione di messaggistica è in fase di sviluppo. Per ora il messaggio sarà simulato.',messagePlaceholder:'Il tuo messaggio...',cancel:'Annulla',sending:'Invio...',send:'Invia',devMessage:'La messaggistica è in fase di sviluppo. Il candidato sarà avvisato prossimamente.',sendError:"Errore durante l'invio del messaggio"},
  ru:{login:'Войдите, чтобы увидеть кандидатов',notFound:'Вакансия не найдена',forbidden:'У вас нет доступа к кандидатам этой вакансии',loadError:'Ошибка загрузки кандидатов',loading:'Поиск подходящих кандидатов...',error:'Ошибка',title:'Подходящие кандидаты',forJob:'Для вакансии:',empty:'Подходящих кандидатов пока нет',emptyHint:'Кандидаты с подходящим профилем появятся здесь автоматически.',beginner:'Начинающий',oneYear:'1 год опыта',years:'лет опыта',why:'Почему этот кандидат?',contact:'Связаться',contactTitle:'Связаться с',note:'Примечание:',noteText:'Функция сообщений находится в разработке. Пока сообщение будет имитироваться.',messagePlaceholder:'Ваше сообщение...',cancel:'Отмена',sending:'Отправка...',send:'Отправить',devMessage:'Функция сообщений находится в разработке. Кандидат скоро получит уведомление.',sendError:'Ошибка отправки сообщения'}
};

export const getCandidateJobMatchTranslations = (language: Language) => candidate[language] || candidate.fr;
export const getCompanyJobMatchTranslations = (language: Language) => company[language] || company.fr;
