import type { Language } from './i18n';

const copy: Record<Language, any> = {
  fr:{mobileSuffix:'sur mobile + inscriptions gratuites !',installHint:'Cliquez sur "Dalil Tounes" pour installer l’application sur votre mobile.',knowUs:'Venez nous connaître',openMenu:'Ouvrir le menu principal',closeMenu:'Fermer le menu principal',iosTitle:'Installer sur iPhone / iPad',close:'Fermer',share:'Appuyez sur le bouton Partager',safariBottom:'en bas de Safari',homeScreen:'Choisissez « Sur l’écran d’accueil »',confirm:'Confirmez en appuyant sur « Ajouter »',safariOnly:'Fonctionne uniquement avec Safari'},
  en:{mobileSuffix:'on mobile + free registrations!',installHint:'Click “Dalil Tounes” to install the app on your phone.',knowUs:'Get to know us',openMenu:'Open main menu',closeMenu:'Close main menu',iosTitle:'Install on iPhone / iPad',close:'Close',share:'Tap the Share button',safariBottom:'at the bottom of Safari',homeScreen:'Choose “Add to Home Screen”',confirm:'Confirm by tapping “Add”',safariOnly:'Works with Safari only'},
  ar:{mobileSuffix:'على الهاتف + تسجيلات مجانية!',installHint:'اضغط على «Dalil Tounes» لتثبيت التطبيق على هاتفك.',knowUs:'تعرّف علينا',openMenu:'فتح القائمة الرئيسية',closeMenu:'إغلاق القائمة الرئيسية',iosTitle:'التثبيت على iPhone / iPad',close:'إغلاق',share:'اضغط على زر المشاركة',safariBottom:'أسفل Safari',homeScreen:'اختر «إضافة إلى الشاشة الرئيسية»',confirm:'أكد بالضغط على «إضافة»',safariOnly:'يعمل فقط مع Safari'},
  it:{mobileSuffix:'su mobile + iscrizioni gratuite!',installHint:'Clicca su “Dalil Tounes” per installare l’app sul telefono.',knowUs:'Scopri chi siamo',openMenu:'Apri il menu principale',closeMenu:'Chiudi il menu principale',iosTitle:'Installa su iPhone / iPad',close:'Chiudi',share:'Tocca il pulsante Condividi',safariBottom:'in basso in Safari',homeScreen:'Scegli “Aggiungi alla schermata Home”',confirm:'Conferma toccando “Aggiungi”',safariOnly:'Funziona solo con Safari'},
  ru:{mobileSuffix:'на телефоне + бесплатная регистрация!',installHint:'Нажмите «Dalil Tounes», чтобы установить приложение на телефон.',knowUs:'Познакомьтесь с нами',openMenu:'Открыть главное меню',closeMenu:'Закрыть главное меню',iosTitle:'Установить на iPhone / iPad',close:'Закрыть',share:'Нажмите кнопку «Поделиться»',safariBottom:'внизу Safari',homeScreen:'Выберите «На экран Домой»',confirm:'Подтвердите, нажав «Добавить»',safariOnly:'Работает только в Safari'}
};

export const getLayoutPublicTranslations = (language: Language) => copy[language] || copy.fr;
