import type { Language } from './i18n';

const copy: Record<Language, any> = {
  fr: { sending:'Envoi en cours...', sendError:"Erreur lors de l'envoi", title:'Proposer mes services', company:'Nom de l’entreprise', companyPlaceholder:'Votre entreprise', sector:'Secteur d’activité', select:'Sélectionnez', description:'Description de vos services', descriptionPlaceholder:'Décrivez vos services, expertise, points forts...', website:'Site web / Portfolio', experience:"Années d’expérience", email:'Email', emailPlaceholder:'votre@email.com', phone:'Téléphone', city:'Ville / Région', send:'Envoyer mon offre', success:'Votre offre a bien été envoyée, merci !', sectors:{ informatique:'Informatique & Tech', marketing:'Marketing & Communication', finance:'Finance & Comptabilité', juridique:'Juridique & Conseil', construction:'Construction & BTP', design:'Design & Créatif', formation:'Formation & Education', sante:'Santé & Bien-être', commerce:'Commerce & Vente', logistique:'Logistique & Transport', autre:'Autre' } },
  en: { sending:'Sending...', sendError:'Error while sending', title:'Offer my services', company:'Company name', companyPlaceholder:'Your company', sector:'Business sector', select:'Select', description:'Description of your services', descriptionPlaceholder:'Describe your services, expertise and strengths...', website:'Website / Portfolio', experience:'Years of experience', email:'Email', emailPlaceholder:'your@email.com', phone:'Phone', city:'City / Region', send:'Send my offer', success:'Your offer has been sent successfully. Thank you!', sectors:{ informatique:'IT & Tech', marketing:'Marketing & Communication', finance:'Finance & Accounting', juridique:'Legal & Consulting', construction:'Construction', design:'Design & Creative', formation:'Training & Education', sante:'Health & Wellness', commerce:'Commerce & Sales', logistique:'Logistics & Transport', autre:'Other' } },
  ar: { sending:'جارٍ الإرسال...', sendError:'خطأ أثناء الإرسال', title:'عرض خدماتي', company:'اسم المؤسسة', companyPlaceholder:'مؤسستك', sector:'قطاع النشاط', select:'اختر', description:'وصف خدماتك', descriptionPlaceholder:'صف خدماتك وخبرتك ونقاط قوتك...', website:'الموقع / معرض الأعمال', experience:'سنوات الخبرة', email:'البريد الإلكتروني', emailPlaceholder:'your@email.com', phone:'الهاتف', city:'المدينة / المنطقة', send:'إرسال عرضي', success:'تم إرسال عرضك بنجاح، شكراً!', sectors:{ informatique:'الإعلامية والتكنولوجيا', marketing:'التسويق والاتصال', finance:'المالية والمحاسبة', juridique:'القانون والاستشارات', construction:'البناء والأشغال', design:'التصميم والإبداع', formation:'التكوين والتعليم', sante:'الصحة والرفاه', commerce:'التجارة والمبيعات', logistique:'اللوجستيك والنقل', autre:'أخرى' } },
  it: { sending:'Invio in corso...', sendError:"Errore durante l'invio", title:'Proporre i miei servizi', company:"Nome dell’impresa", companyPlaceholder:'La tua impresa', sector:'Settore di attività', select:'Seleziona', description:'Descrizione dei servizi', descriptionPlaceholder:'Descrivi servizi, competenze e punti di forza...', website:'Sito web / Portfolio', experience:'Anni di esperienza', email:'Email', emailPlaceholder:'tua@email.com', phone:'Telefono', city:'Città / Regione', send:'Invia la mia offerta', success:'La tua offerta è stata inviata con successo. Grazie!', sectors:{ informatique:'Informatica & Tech', marketing:'Marketing & Comunicazione', finance:'Finanza & Contabilità', juridique:'Legale & Consulenza', construction:'Edilizia', design:'Design & Creatività', formation:'Formazione & Istruzione', sante:'Salute & Benessere', commerce:'Commercio & Vendite', logistique:'Logistica & Trasporti', autre:'Altro' } },
  ru: { sending:'Отправка...', sendError:'Ошибка отправки', title:'Предложить свои услуги', company:'Название компании', companyPlaceholder:'Ваша компания', sector:'Сфера деятельности', select:'Выберите', description:'Описание ваших услуг', descriptionPlaceholder:'Опишите услуги, опыт и сильные стороны...', website:'Сайт / Портфолио', experience:'Лет опыта', email:'Email', emailPlaceholder:'your@email.com', phone:'Телефон', city:'Город / Регион', send:'Отправить предложение', success:'Ваше предложение успешно отправлено. Спасибо!', sectors:{ informatique:'IT и технологии', marketing:'Маркетинг и коммуникации', finance:'Финансы и бухгалтерия', juridique:'Право и консалтинг', construction:'Строительство', design:'Дизайн и креатив', formation:'Обучение и образование', sante:'Здоровье и благополучие', commerce:'Торговля и продажи', logistique:'Логистика и транспорт', autre:'Другое' } },
};

export function getPartnerSearchOfferTranslations(language: Language) {
  return copy[language] || copy.fr;
}
