import type { Language } from './i18n';

const translations: Record<Language, any> = {
  fr: {
    loadingProfile: 'Chargement de la fiche...', back: 'Retour', freeProfile: 'Fiche gratuite Dalil Tounes', backServices: 'Retour aux services', home: 'Accueil', reviewsLoading: 'Chargement des avis...', reviewsTitle: 'Avis clients', reviewsEmpty: 'Aucun avis pour le moment.', anonymous: 'Anonyme', previous: 'Précédent', next: 'Suivant', topRecommendedPrefix: 'Entreprises les plus recommandées par les clients à', topRecommendedSubtitle: 'Les mieux notées par la communauté', ratingUnavailable: 'Note non disponible', noProfessional: 'Aucun professionnel référencé pour le moment.', rankingInfo: "Les classements reposent sur des critères automatisés (avis publics, notes Google, volume d'avis).", learnMore: 'En savoir plus', googleReviews: 'Voir les avis Google', qrAlways: 'Votre QR toujours avec vous', installQr: 'Installer mon QR', installIos: 'Sur iPhone : Safari → Partager → Ajouter à l’écran d’accueil.', installAndroid: 'Sur Android : Chrome → Menu → Installer l’application ou Ajouter à l’écran d’accueil.', qrNote: 'Ouvrez cette vitrine directement depuis votre écran d’accueil.',
  },
  en: {
    loadingProfile: 'Loading profile...', back: 'Back', freeProfile: 'Free Dalil Tounes profile', backServices: 'Back to services', home: 'Home', reviewsLoading: 'Loading reviews...', reviewsTitle: 'Customer reviews', reviewsEmpty: 'No reviews yet.', anonymous: 'Anonymous', previous: 'Previous', next: 'Next', topRecommendedPrefix: 'Businesses most recommended by customers in', topRecommendedSubtitle: 'Top rated by the community', ratingUnavailable: 'Rating unavailable', noProfessional: 'No professional listed yet.', rankingInfo: 'Rankings are based on automated criteria (public reviews, Google ratings, review volume).', learnMore: 'Learn more', googleReviews: 'View Google reviews', qrAlways: 'Your QR always with you', installQr: 'Install my QR', installIos: 'On iPhone: Safari → Share → Add to Home Screen.', installAndroid: 'On Android: Chrome → Menu → Install app or Add to Home Screen.', qrNote: 'Open this profile directly from your home screen.',
  },
  ar: {
    loadingProfile: 'جارٍ تحميل البطاقة...', back: 'رجوع', freeProfile: 'بطاقة دليل تونس المجانية', backServices: 'العودة إلى الخدمات', home: 'الرئيسية', reviewsLoading: 'جارٍ تحميل الآراء...', reviewsTitle: 'آراء العملاء', reviewsEmpty: 'لا توجد آراء حتى الآن.', anonymous: 'مجهول', previous: 'السابق', next: 'التالي', topRecommendedPrefix: 'المؤسسات الأكثر توصية من العملاء في', topRecommendedSubtitle: 'الأعلى تقييماً من المجتمع', ratingUnavailable: 'التقييم غير متوفر', noProfessional: 'لا يوجد مهني مدرج حالياً.', rankingInfo: 'تعتمد التصنيفات على معايير آلية (الآراء العامة، تقييمات Google، وعدد الآراء).', learnMore: 'اعرف المزيد', googleReviews: 'عرض آراء Google', qrAlways: 'رمز QR الخاص بك معك دائماً', installQr: 'تثبيت رمز QR', installIos: 'على iPhone: Safari ← مشاركة ← إضافة إلى الشاشة الرئيسية.', installAndroid: 'على Android: Chrome ← القائمة ← تثبيت التطبيق أو الإضافة إلى الشاشة الرئيسية.', qrNote: 'افتح هذه البطاقة مباشرة من شاشتك الرئيسية.',
  },
  it: {
    loadingProfile: 'Caricamento della scheda...', back: 'Indietro', freeProfile: 'Scheda gratuita Dalil Tounes', backServices: 'Torna ai servizi', home: 'Home', reviewsLoading: 'Caricamento delle recensioni...', reviewsTitle: 'Recensioni dei clienti', reviewsEmpty: 'Nessuna recensione per il momento.', anonymous: 'Anonimo', previous: 'Precedente', next: 'Successivo', topRecommendedPrefix: 'Le imprese più consigliate dai clienti a', topRecommendedSubtitle: 'Le più apprezzate dalla comunità', ratingUnavailable: 'Valutazione non disponibile', noProfessional: 'Nessun professionista presente al momento.', rankingInfo: 'Le classifiche si basano su criteri automatici (recensioni pubbliche, valutazioni Google, volume delle recensioni).', learnMore: 'Scopri di più', googleReviews: 'Vedi le recensioni Google', qrAlways: 'Il tuo QR sempre con te', installQr: 'Installa il mio QR', installIos: 'Su iPhone: Safari → Condividi → Aggiungi alla schermata Home.', installAndroid: 'Su Android: Chrome → Menu → Installa app o Aggiungi alla schermata Home.', qrNote: 'Apri questa vetrina direttamente dalla schermata Home.',
  },
  ru: {
    loadingProfile: 'Загрузка карточки...', back: 'Назад', freeProfile: 'Бесплатная карточка Dalil Tounes', backServices: 'Назад к услугам', home: 'Главная', reviewsLoading: 'Загрузка отзывов...', reviewsTitle: 'Отзывы клиентов', reviewsEmpty: 'Отзывов пока нет.', anonymous: 'Аноним', previous: 'Предыдущий', next: 'Следующий', topRecommendedPrefix: 'Компании, которые чаще всего рекомендуют клиенты в', topRecommendedSubtitle: 'Лучшие оценки сообщества', ratingUnavailable: 'Оценка недоступна', noProfessional: 'Пока нет зарегистрированных специалистов.', rankingInfo: 'Рейтинг формируется автоматически на основе публичных отзывов, оценок Google и их количества.', learnMore: 'Подробнее', googleReviews: 'Посмотреть отзывы Google', qrAlways: 'Ваш QR всегда с вами', installQr: 'Установить мой QR', installIos: 'На iPhone: Safari → Поделиться → На экран «Домой».', installAndroid: 'На Android: Chrome → Меню → Установить приложение или Добавить на главный экран.', qrNote: 'Открывайте эту карточку прямо с главного экрана.',
  },
};

export function getPublicComponentTranslations(language: Language) {
  return translations[language] || translations.fr;
}
