import { PARTNERSHIP_RATES } from '../config/partnership';

export const partnerPageCopy = {
  fr: {
    seoTitle: 'Devenir partenaire commercial | Dalil Tounes', seoDescription: 'Rejoignez les partenaires commerciaux indépendants de Dalil Tounes et accompagnez les professionnels avec le Modèle Professionnel ou le Modèle Portfolio.',
    badge: 'Partenariat commercial indépendant', title: 'Devenez partenaire commercial Dalil Tounes', intro: 'Aidez les professionnels tunisiens à mieux présenter leur activité et à gagner en visibilité avec une présence claire et professionnelle.', reward: `Jusqu’à ${PARTNERSHIP_RATES.completeSale} % de rémunération selon votre implication.`, cta: 'Présenter ma candidature', note: 'Activité indépendante, sans exclusivité et sans engagement de volume.',
    solutionEyebrow: 'La solution que vous présentez', solutionTitle: 'Deux modèles pour valoriser chaque métier', solutionIntro: 'Le professionnel choisit la présentation la plus adaptée à son activité, à ses contenus et à la manière dont il souhaite convaincre ses clients.', professional: 'Modèle Professionnel', professionalText: 'Clair, structuré et direct. Il rassemble les informations utiles, les services et les moyens de contact.', portfolio: 'Modèle Portfolio', portfolioText: 'Plus visuel, il valorise les photos, les réalisations et le savoir-faire du professionnel.',
    offersEyebrow: 'Deux façons de collaborer', offersTitle: 'Choisissez votre niveau d’implication', lead: 'Recommandation qualifiée', leadText: 'Vous identifiez un professionnel intéressé et organisez une mise en relation sérieuse avec Dalil Tounes.', sale: 'Vente complète accompagnée', saleText: 'Vous présentez l’offre, accompagnez le choix du modèle et suivez le professionnel jusqu’à la commande.', leadTasks: ['Présenter brièvement la solution', 'Vérifier le besoin et l’intérêt', 'Transmettre un contact qualifié'], saleTasks: ['Comprendre l’activité du client', 'Présenter les deux modèles', 'Accompagner la décision'], legal: 'Les pourcentages correspondent à la mission réellement accomplie. Les modalités précises sont confirmées avant le démarrage du partenariat.',
    stepsEyebrow: 'Un parcours simple', stepsTitle: 'Comment devenir partenaire ?', steps: [['Candidatez', 'Présentez votre profil, votre gouvernorat et votre expérience.'], ['Échangeons', 'Nous vérifions ensemble que le partenariat vous correspond.'], ['Recevez vos outils', 'Découvrez les offres, les exemples et la méthode Dalil Tounes.'], ['Développez votre réseau', 'Recommandez Dalil Tounes en toute indépendance.']],
    supportEyebrow: 'Vous n’êtes pas seul', supportTitle: 'Ce que Dalil Tounes met à votre disposition', support: [['Argumentaire clair', 'Une présentation simple à comprendre et à transmettre.'], ['Exemples concrets', 'Les deux modèles à montrer en situation réelle.'], ['Accompagnement', 'Un interlocuteur pour répondre à vos questions.'], ['Cadre transparent', 'Des missions et une rémunération définies avant de commencer.']],
    profilesEyebrow: 'Profils recherchés', profilesTitle: 'Vous connaissez bien les professionnels de votre région ?', profiles: ['Commercial indépendant', 'Apporteur d’affaires', 'Consultant', 'Professionnel du digital', 'Acteur associatif', 'Réseau local'], location: 'Candidatures ouvertes dans tous les gouvernorats de Tunisie.',
    formEyebrow: 'Votre candidature', formTitle: 'Parlons de votre projet de partenariat', formIntro: 'Quelques informations suffisent pour préparer un premier échange. Aucun dossier n’est envoyé depuis cette version Preview.', fields: { name: 'Nom et prénom', email: 'E-mail', phone: 'Téléphone / WhatsApp', governorate: 'Gouvernorat', zone: 'Zone commerciale souhaitée', activity: 'Activité actuelle', partnership: 'Type de partenariat souhaité', experience: 'Expérience commerciale', network: 'Votre réseau professionnel', link: 'Site ou profil professionnel', message: 'Votre message' }, select: 'Sélectionnez', options: [`Recommandation qualifiée — ${PARTNERSHIP_RATES.qualifiedLead} %`, `Vente complète accompagnée — ${PARTNERSHIP_RATES.completeSale} %`, 'Je souhaite en discuter'], consent: 'J’accepte que ces informations soient utilisées pour étudier ma demande de partenariat.', privacy: 'Politique de confidentialité', submit: 'Préparer ma demande', required: 'Ce champ est obligatoire.', consentError: 'Votre accord est nécessaire.', emailError: 'Saisissez une adresse e-mail valide.', success: 'Votre demande a bien été préparée. Dans cette version Preview, aucune donnée n’a encore été transmise.',
    faqEyebrow: 'Questions fréquentes', faqTitle: 'Avant de vous lancer', faq: [['Faut-il être commercial professionnel ?', 'Non. Nous recherchons surtout des personnes sérieuses, à l’aise avec le contact humain et capables de présenter clairement Dalil Tounes.'], ['Comment fonctionne la rémunération ?', 'La recommandation qualifiée ouvre droit à 10 % et la vente complète accompagnée à 25 %, selon les conditions du partenariat.'], ['Puis-je choisir ma zone ?', 'Oui. Vous indiquez le ou les gouvernorats dans lesquels votre réseau est le plus actif.'], ['Suis-je exclusif de Dalil Tounes ?', 'Non. Le partenariat est indépendant et sans exclusivité.'], ['Quels outils vais-je recevoir ?', 'Dalil Tounes fournit une présentation claire, des exemples, des supports commerciaux et un accompagnement.']], finalTitle: 'Prêt à développer Dalil Tounes dans votre région ?', finalText: 'Présentez votre candidature et échangeons simplement sur votre expérience, votre réseau et vos ambitions.', footerLink: 'Devenir partenaire',
  },
  ar: {
    seoTitle: 'كن شريكاً تجارياً | دليل تونس', seoDescription: 'انضم إلى شبكة الشركاء التجاريين المستقلين لدليل تونس وساعد المهنيين على اختيار النموذج المهني أو نموذج معرض الأعمال.',
    badge: 'شراكة تجارية مستقلة', title: 'كن شريكاً تجارياً لدليل تونس', intro: 'ساعد المهنيين التونسيين على تقديم أنشطتهم بشكل أفضل وتعزيز ظهورهم بحضور واضح واحترافي.', reward: `عمولة تصل إلى ${PARTNERSHIP_RATES.completeSale}% حسب مستوى مساهمتك.`, cta: 'قدّم ترشحك', note: 'نشاط مستقل، دون حصرية ودون التزام بحجم مبيعات.',
    solutionEyebrow: 'الحل الذي ستقدّمه', solutionTitle: 'نموذجان لإبراز كل مهنة', solutionIntro: 'يختار المهني العرض الأنسب لنشاطه ومحتواه والطريقة التي يريد بها إقناع عملائه.', professional: 'النموذج المهني', professionalText: 'واضح ومنظم ومباشر، يجمع المعلومات والخدمات ووسائل الاتصال الأساسية.', portfolio: 'نموذج معرض الأعمال', portfolioText: 'عرض بصري يبرز الصور والإنجازات والخبرة المهنية.',
    offersEyebrow: 'طريقتان للتعاون', offersTitle: 'اختر مستوى مساهمتك', lead: 'إحالة مؤهلة', leadText: 'تحدد مهنياً مهتماً وتنظم تواصلاً جدياً مع دليل تونس.', sale: 'بيع كامل مع المرافقة', saleText: 'تقدم العرض وترافق اختيار النموذج وتتابع المهني حتى إتمام الطلب.', leadTasks: ['تقديم الحل باختصار', 'التأكد من الحاجة والاهتمام', 'إرسال جهة اتصال مؤهلة'], saleTasks: ['فهم نشاط العميل', 'تقديم النموذجين', 'مرافقة اتخاذ القرار'], legal: 'ترتبط النسب بالمهمة المنجزة فعلياً، وتُؤكّد التفاصيل قبل بدء الشراكة.',
    stepsEyebrow: 'مسار بسيط', stepsTitle: 'كيف تصبح شريكاً؟', steps: [['قدّم ترشحك', 'عرّف بنفسك وبولايتك وخبرتك.'], ['نتواصل معك', 'نتأكد معاً من ملاءمة الشراكة لك.'], ['تستلم أدواتك', 'تتعرف على العروض والأمثلة وطريقة دليل تونس.'], ['تطوّر شبكتك', 'توصي بدليل تونس باستقلالية كاملة.']],
    supportEyebrow: 'لست وحدك', supportTitle: 'ما الذي يضعه دليل تونس على ذمتك؟', support: [['عرض واضح', 'شرح بسيط يسهل فهمه ونقله.'], ['أمثلة واقعية', 'النموذجان في حالات تطبيقية.'], ['مرافقة', 'جهة اتصال للإجابة عن أسئلتك.'], ['إطار شفاف', 'مهام وعمولة محددتان قبل البدء.']],
    profilesEyebrow: 'الملفات المطلوبة', profilesTitle: 'هل تعرف مهنيي منطقتك جيداً؟', profiles: ['تجاري مستقل', 'وسيط أعمال', 'مستشار', 'مختص رقمي', 'فاعل جمعياتي', 'شبكة محلية'], location: 'الترشحات مفتوحة في جميع ولايات تونس.',
    formEyebrow: 'ترشحك', formTitle: 'حدثنا عن مشروع الشراكة', formIntro: 'تكفي بعض المعلومات لإعداد أول تواصل. لا يتم إرسال أي ملف في نسخة المعاينة هذه.', fields: { name: 'الاسم واللقب', email: 'البريد الإلكتروني', phone: 'الهاتف / واتساب', governorate: 'الولاية', zone: 'المنطقة التجارية المطلوبة', activity: 'النشاط الحالي', partnership: 'نوع الشراكة المطلوبة', experience: 'الخبرة التجارية', network: 'شبكتك المهنية', link: 'الموقع أو الملف المهني', message: 'رسالتك' }, select: 'اختر', options: [`إحالة مؤهلة — ${PARTNERSHIP_RATES.qualifiedLead}%`, `بيع كامل مع المرافقة — ${PARTNERSHIP_RATES.completeSale}%`, 'أرغب في مناقشة الأمر'], consent: 'أوافق على استخدام هذه المعلومات لدراسة طلب الشراكة.', privacy: 'سياسة الخصوصية', submit: 'إعداد طلبي', required: 'هذا الحقل إجباري.', consentError: 'موافقتك ضرورية.', emailError: 'أدخل بريداً إلكترونياً صحيحاً.', success: 'تم إعداد طلبك. في نسخة المعاينة هذه، لم يتم إرسال أي بيانات بعد.',
    faqEyebrow: 'أسئلة شائعة', faqTitle: 'قبل أن تبدأ', faq: [['هل يجب أن أكون تجارياً محترفاً؟', 'لا. نبحث خصوصاً عن أشخاص جادين يجيدون التواصل وتقديم دليل تونس بوضوح.'], ['كيف تعمل العمولة؟', 'تبلغ العمولة 10% للإحالة المؤهلة و25% للبيع الكامل مع المرافقة، وفق شروط الشراكة.'], ['هل يمكنني اختيار منطقتي؟', 'نعم، يمكنك تحديد الولاية أو الولايات التي تنشط فيها شبكتك.'], ['هل الشراكة حصرية؟', 'لا، الشراكة مستقلة ودون حصرية.'], ['ما الأدوات التي سأحصل عليها؟', 'يوفر دليل تونس عرضاً واضحاً وأمثلة ودعماً تجارياً ومرافقة.']], finalTitle: 'هل أنت مستعد لتطوير دليل تونس في منطقتك؟', finalText: 'قدّم ترشحك ولنتحدث ببساطة عن خبرتك وشبكتك وطموحاتك.', footerLink: 'كن شريكاً',
  },
} as const;
